# Generated by Django 5.1.4 on 2025-01-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('department', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('personnel_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=11)),
                ('expertise', models.CharField(blank=True, max_length=100, null=True)),
                ('current_tasks', models.PositiveIntegerField(blank=True, default=0)),
                ('satisfaction', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesManager',
            fields=[
                ('identifier', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Facilities_images/')),
                ('task_categories', models.ManyToManyField(to='core.taskcategory')),
                ('workers', models.ManyToManyField(to='core.worker')),
            ],
            options={
                'unique_together': {('organization', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'در انتظار'), ('In Progress', 'در حال انجام'), ('Completed', 'تکمیل شده')], max_length=50)),
                ('requester_description', models.TextField()),
                ('worker_description', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilitiesmanager')),
                ('category', models.ManyToManyField(to='core.taskcategory')),
                ('current_worker', models.ManyToManyField(to='core.worker')),
            ],
        ),
    ]
