# Generated by Django 5.1.4 on 2025-01-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_estimated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='core.taskcategory'),
            preserve_default=False,
        ),
    ]
