# Generated by Django 5.1.4 on 2025-01-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_category_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_worker',
            field=models.ManyToManyField(blank=True, related_name='current_worker', to='core.worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
